name: Dispatch check for patch conflicts
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
      - "v*.*.*"
      - "release-*"

jobs:
  dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Dispatch job"
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'actions-security-demo',
                repo: 'poc-2',
                workflow_id: 'test.yml',
                ref: 'main',
                inputs: {
                  src_repo: "${{ github.repository }}",
                  src_ref: "${{ github.head_ref }}",
                  src_merge_sha: "${{ github.sha }}",
                  src_pr_commit_sha: "${{ github.event.pull_request.head.sha }}",
                  patch_repo: "${{ github.repository }}-security-patches",
                  patch_ref: "${{ github.base_ref }}",
                  triggering_github_handle: "${{ github.event.sender.login }}"
                }
            })
